# Run test Code
name: Test NCG Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Clone CircuitGame
        run: |
          git clone https://github.com/neknaj/circuitgame.git
          cd circuitgame
          npm run install-rust
          
      - name: Build CircuitGame
        run: |
          npm run build

      - name: Run NCG Test (bem)
        run: |
          ./ncg -i circuit/small_stack_machine.ncg -o test/module/small_stack_machine.ts -m .+
          node build.js
          bun run test/test.js
          
      - name: Run NCG Test (wogikaze)
        run: |
          ./ncg -i circuit/turing_complete/turing_complete.ncg -o test/module/turing_complete.ts -m .+
          npm run test
